In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

import datetime

In [2]:
df_dummy = pd.read_csv('dummy_def.csv', delimiter = ';') 
df_dummy

,object_id,incident,nr_of_accomodations_in_building,nr_of_residential_accomodations_in_building,floorsize_accomodation,construction_year,timeline,function,situation,ownership,is_monument,neighborhood,nr_of_inspections_within_timeline,nr_of_inspections_with_observation,nr_of_inspections_without_observation
0,1b47f57e7692d3c095345d98bfd85b1c06dd9c268d5dd4...,0,15,13,29,983,31/12/9999,Woning|Berging/schuur,Tussengebouw,Huur,0,Anjeliersbuurt,0,0,0
1,1b47f57e7692d3c095345d98bfd85b1c06dd9c268d5dd4...,0,14,4,19,983,31/12/9999,Woning|Berging/schuur,Tussengebouw,Huur,0,Anjeliersbuurt Zuid,0,0,0
2,4db936db50deabc74a224621503fc16465e29f23fcb595...,0,10,8,51,983,31/12/9999,Woning|Berging/schuur,Tussengebouw,Huur,0,Anjeliersbuurt,0,0,0
3,4db936db50deabc74a224621503fc16465e29f23fcb595...,0,15,3,36,983,31/12/9999,Woning|Berging/schuur,Tussengebouw,Huur,0,Anjeliersbuurt Zuid,0,0,0
4,4db936db50deabc74a224621503fc16465e29f23fcb595...,0,10,8,18,983,18/06/2012,woning,Tussengebouw,Huur,0,Anjeliersbuurt,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188803,82dc2820e82c5b79e6876209e83c802ac36fbf8d72b5f1...,0,4,0,415,1836,31/12/9999,Kantoor|Opslag/magazijn,Vrijstaand gebouw,Huur,1,Van der Pekbuurt,6,1,5
188804,91d8b28b71969b077b037223083a833f95d2f0a0e3c75e...,0,4,1,1507,1615,31/12/9999,Kantoor,Tussengebouw,Eigendom,0,Leliegracht e.o.,1,0,1
188805,1f44551055c236017d222f45189196ba7ab2bd2a0c38f7...,0,4,3,22194,1618,31/12/9999,Overige ruimten,Vrijstaand gebouw,Huur,0,Nieuwe Kerk e.o.,3,2,1
188806,f7897f3ba448a860eb0ee2909324d5dd5e20b1e863bd03...,0,26,25,36,1712,09/08/2013,Woning,Tussengebouw,Huur,0,Weesperbuurt,1,0,1
188807,f7897f3ba448a860eb0ee2909324d5dd5e20b1e863bd03...,0,22,10,25,1712,31/12/9999,Woning,Tussengebouw,Huur,0,Weesperbuurt,4,2,2

In [3]:
df_dummy = df_dummy.replace({'woning':'Woning', 'kantoor':'Kantoor', 
                             'kantoor in bedrijfsverzamelgebouw':'Kantoor in bedrijfsverzamelgebouw', 
                             'cafÃƒÂ© / bar / restaurant':'Cafe/bar/restaurant', 
                             'cafÃ¯Â¿Â½Ã¯Â¿Â½ / bar / restaurant':'Cafe/bar/restaurant', 'terrein':'Terrein', 'museum':'Museum', 
                            'overig medisch':'Overig medisch', 'medisch':'Medisch', 'winkel':'Winkel', 'garage':'Garage', 
                            'Verzorgings- / bejaardentehuis (complex)':'Verzorgings-/bejaardentehuis', 'hotel / motel':'Hotel/motel',
                            'basisschool':'Basisschool', 'cultuur':'Cultuur', 'atelier / werkruimte':'Atelier/werkruimte', 
                            'trafo':'Trafo', 'dagverblijf':'Creche', 'crÃ¯Â¿Â½Ã¯Â¿Â½che / peuterspeelzaal':'Creche/peuterspeelzaal', 
                            'gezinsvervangend tehuis':'Gezinsvervangend tehuis', 
                             'parkeerplaats (niet dienstbaar aan wonen)':'Parkeerplaats (niet dienstbaar wonen)', 
                            'praktijkruimte':'Praktijkruimte', 'beroepsonderwijs  (LBO / MBO)':'Beroepsonderwijs (LBO/MBO)', 
                            'hogeschool / universiteit':'Hogeschool/universiteit', 'algemeen voortgezet onderwijs  (MAVO / HAVO /':
                            'Algemeen voortgezet onderwijs (MAVO/HAVO/VWO)', 'kerk':'Kerk', 'onderwijs':'Onderwijs', 'sport / recreatie':
                            'Sport/recreatie', 'wijk- / buurtcentrum':'Wijk-/buurtcentrum', 'recreatie / sportcentrum':'Recreatie/sportcentrum',
                            'bedrijf':'Bedrijf', 'horeca':'Horeca', 'overig bedrijf':'Overig bedrijf', 'opslag / distributie':'Opslag/distributie',
                            'verzorgings- / bejaardentehuis (complex)':'Verzorgings-/bejaardentehuis', 'woning + bedrijf (overig)':'Woning + bedrijf', 
                            'woning + bedrijf':'Woning + bedrijf', 'woning + horeca':'Woning + horeca', 'sporthal / sportzaal / gymnastieklokaal':
                            'Sporthal/sportzaal/gymnastieklokaal', 'speciaal onderwijs':'Speciaal onderwijs', 'woning + (detail)handel / winkel':
                            'Woning + (detail)handel/winkel', 'dienstverlening openbaar nut':'Dienstverlening openbaar nut', '(detail)handel / winkel':
                             '(Detail)handel/winkel', 'bijzondere woonfunctie':'Bijzondere woonfunctie', 'parkeergarage geÃ¯Â¿Â½Ã¯Â¿Â½xploiteerd voor kortparkeren':
                             'Parkeergarage geexploiteerd voor kortparkeren', 'Opslag/magazijn|Werkruimte':'Opslag/magazijn|Werkplaats',
                            'kantoor (hoofdcode)':'Kantoor', 'Dagverblijf':'Creche'})

In [4]:
pd.options.display.max_rows = 165
df_dummy['function'].value_counts()

Woning                                                    111376
Woning|Berging/schuur                                      36807
Kantoor                                                     5437
Woning|Berging/schuur onderpandig                           3631
Garage                                                      2570
Winkel/verkoopruimte                                        2328
Woning|Dakterras                                            2166
Woning|Balkon                                               1820
Woning|Zolder                                               1585
(Detail)handel/winkel                                       1498
Bedrijf                                                     1229
Winkel/verkoopruimte|Opslag/magazijn                        1110
Opslag/magazijn                                              935
Winkel                                                       792
Woning|Dakterras|Berging/schuur                              763
Kantoor in bedrijfsverzamelgebouw                            746
Kantoor|Opslag/magazijn                                      716
Restaurant                                                   667
Werkruimte                                                   595
Woning|Zolder|Berging/schuur                                 564
Horeca                                                       493
Overig bedrijf                                               453
Woning|Woningdeel overig                                     429
Opslag/distributie                                           405
Woning|Kelder                                                369
Hotel/motel                                                  362
Woning|Balkon|Berging/schuur onderpandig                     342
Opstal                                                       320
Woning|Berging/schuur inpandig                               318
Werkplaats                                                   315
Trafo                                                        305
Cafe/bar/restaurant                                          301
Woning|Dakterras|Berging/schuur onderpandig                  296
Restaurant|Opslag/magazijn                                   281
Praktijkruimte                                               268
Verzorgings-/bejaardentehuis                                 243
Woning|Kelder|Berging/schuur                                 222
Hotelkamer                                                   220
Kantoor|Werkruimte                                           194
Schoolgebouw                                                 180
Creche                                                       175
Basisschool                                                  174
Atelier/werkruimte                                           172
Winkel/verkoopruimte|Kantoor|Opslag/magazijn                 155
Parkeerplaats                                                150
Cafe/bar                                                     141
Cultuur                                                      135
Woning|Inpandige garage                                      122
Woning|Balkon|Berging/schuur                                 119
In aanbouw                                                   103
Woning|Woningdeel overig|Berging/schuur                       99
Winkel/verkoopruimte|Kantoor                                  91
Cafetaria                                                     89
Club-/verenigingsgebouw                                       89
Kantoor|Werkplaats                                            75
Restaurant|Keuken                                             72
Sport/recreatie                                               70
Overige ruimten                                               69
Onderpandige garage                                           67
Woning|Tuin bij meergezinswoning                              64
Cafe/bar|Opslag/magazijn                                      62
Restaurant|Opslag/magazijn|Keuken                             61
Opslag/magazijn|Werkplaats                                    61
Zaal/Collegezaal                                              60
Stadsverwarmingsinstallatie                                   58
Gymzaal|Schoolgebouw                                          56
Parkeergarage geexploiteerd voor kortparkeren                 54
Woning|Berging/schuur aangebouwd                              53
Kerk                                                          52
Woning|Dakterras|Inpandige garage                             52
Onderwijs                                                     52
Woning|Garage                                                 49
Winkel/verkoopruimte|Werkruimte                               49
Woning|Berging/schuur onderpandig|Parkeerplaats               49
Parkeerplaats (niet dienstbaar wonen)                         48
Woning|Berging/schuur vrijstaand                              48
Woning + bedrijf                                              47
Cafetaria|Opslag/magazijn                                     46
Algemeen voortgezet onderwijs (MAVO/HAVO/VWO)                 46
Gezinsvervangend tehuis                                       45
Woning|Dakkapel                                               45
Woning|Woningdeel overig|Dakterras                            42
Berging/schuur                                                42
Creche/peuterspeelzaal                                        42
Woning|Aanbouw woonruimte|Dakkapel                            39
Gebouwdeel t.b.v. woondoeleinden in g                         38
Woning|Woningdeel overig|Zolder                               37
Atelier                                                       36
Beroepsonderwijs (LBO/MBO)                                    36
Opslag/magazijn|Praktijkruimte                                36
Woning|Berging/schuur|Parkeerplaats                           36
Woning|Onderpandige garage                                    35
Ontspanningsruimte                                            35
Kantoor|Opslag/magazijn|Werkplaats                            35
Hogeschool/universiteit                                       35
Dienstverlening openbaar nut                                  34
Woning|Aanbouw woonruimte                                     34
Woning|Garage aangebouwd                                      32
Woning|Zolder|Kelder                                          32
Sportzaal                                                     31
Kantoor|Sanitaire ruimte                                      31
Kantoor|Technische installatieruimte                          30
Woning|Dakterras|Zolder                                       29
Kantoor|Opslag/magazijn|Werkruimte                            29
Fitnessruimte                                                 29
Woning|Dakterras|Balkon                                       29
Woning + (detail)handel/winkel                                28
Wijk-/buurtcentrum                                            28
Technische installatieruimte                                  28
Woning|Garage|Berging/schuur                                  28
Recreatie/sportcentrum                                        27
Woning|Berging/schuur|Berging/schuur onderpandig              27
Kantoor|Restaurant|Opslag/magazijn                            27
Kantoor|Entree/garderobe|Opslag/magazijn                      26
Woning|Balkon|Berging/schuur onderpandig|Parkeerplaats        26
Woning|Berging/schuur|Opslag/magazijn                         26
Speciaal onderwijs                                            25
Sporthal/sportzaal/gymnastieklokaal                           25
Winkel/verkoopruimte|Kantine|Opslag/magazijn                  25
Winkel/verkoopruimte|Opslag/magazijn|Dagverblijf              25
Productieruimte                                               24
Bijzondere woonfunctie                                        24
Kerkzaal (gebedsruimte)                                       24
Expositieruimte                                               24
Winkel/verkoopruimte|Dagverblijf                              24
Kantoor|Productieruimte                                       23
Gymzaal                                                       22
Parkeerplaats|Kantoor|Opslag/magazijn                         22
Hotelkamer|Overige ruimten                                    22
Woning|Zolder|Kelder|Berging/schuur                           21
Restaurant|Sanitaire ruimte|Opslag/magazijn|Keuken            21
Zaal (horeca)                                                 21
Woning|Parkeerplaats                                          21
Kantoor|Opslag/magazijn|Overige ruimten                       21
Onderpandige garage|Parkeerplaats                             21
Medisch                                                       20
Woning + horeca                                               20
Hotelkamer|Entree/garderobe                                   20
Woning|Dakterras|Berging/schuur inpandig                      20
Overig medisch                                                20
Museum                                                        20
Woning|Woningdeel overig|Kelder                               19
Terrein                                                       18
Woning|Dakterras|Kelder                                       17
Woning|Inpandige garage|Berging/schuur                        16
Woning|Winkel/verkoopruimte|Opslag/magazijn                   14
Woning|Winkel/verkoopruimte                                   12
Woning in niet-woning|Winkel/verkoopruimte                    12
Woning|Kantoor                                                12
Woning|Balkon|Parkeerplaats                                    7
Woning|Dakterras|Botenhuis                                     6
Woning|Dakterras|Garage aangebouwd                             4
Woning|Balkon|Inpandige garage                                 3
Woning|Carport                                                 3
Name: function, dtype: int64

In [5]:
df_dummy['woning'] = (df_dummy['function'].isin(["Woning", "Woning|Berging/schuur", "Woning|Berging/schuur onderpandig", 
                                                     "Woning|Dakterras", "Woning|Balkon", "Woning|Zolder", "Woning|Dakterras|Berging/schuur", 
                                                     "Woning|Zolder|Berging/schuur", "Woning|Woningdeel overig", "Woning|Kelder", 
                                                     "Woning|Balkon|Berging/schuur onderpandig", "Woning|Berging/schuur inpandig",
                                                     "Woning|Dakterras|Berging/schuur onderpandig", "Woning|Kelder|Berging/schuur", 
                                                     "Woning|Inpandige garage", "Woning|Balkon|Berging/schuur", "Woning|Woningdeel overig|Berging/schuur", 
                                                     "Woning|Tuin bij meergezinswoning", "Woning|Berging/schuur aangebouwd", 
                                                     "Woning|Dakterras|Inpandige garage", "Woning|Garage", "Woning|Berging/schuur onderpandig|Parkeerplaats", 
                                                     "Woning|Berging/schuur vrijstaand", "Woning + bedrijf", "Woning|Dakkapel", "Woning|Woningdeel overig|Dakterras", 
                                                     "Woning|Aanbouw woonruimte|Dakkapel", "Woning|Woningdeel overig|Zolder", 
                                                     "Woning|Berging/schuur|Parkeerplaats", "Woning|Onderpandige garage", 
                                                     "Woning|Aanbouw woonruimte", "Woning|Garage aangebouwd", "Woning|Zolder|Kelder", 
                                                     "Woning|Dakterras|Zolder", "Woning|Dakterras|Balkon", "Woning + (detail)handel/winkel", 
                                                     "Woning|Garage|Berging/schuur", "Woning|Berging/schuur|Berging/schuur onderpandig", 
                                                     "Woning|Balkon|Berging/schuur onderpandig|Parkeerplaats", "Woning|Berging/schuur|Opslag/magazijn", 
                                                     "Woning|Zolder|Kelder|Berging/schuur", "Woning|Parkeerplaats", "Woning + horeca", 
                                                     "Woning|Dakterras|Berging/schuur inpandig", "Woning|Woningdeel overig|Kelder", 
                                                     "Woning|Dakterras|Kelder", "Woning|Inpandige garage|Berging/schuur", 
                                                     "Woning|Winkel/verkoopruimte|Opslag/magazijn", "Woning|Winkel/verkoopruimte", 
                                                     "Woning in niet-woning|Winkel/verkoopruimte", "Woning|Kantoor", "Woning|Balkon|Parkeerplaats", 
                                                     "Woning|Dakterras|Botenhuis", "Woning|Dakterras|Garage aangebouwd", "Woning|Balkon|Inpandige garage", 
                                                     "Woning|Balkon|Inpandige garage", "Woning|Carport"]))
df_dummy['woning'] = list(map(int, df_dummy['woning']))
df_dummy['woning'].value_counts()

1    162122
0     26686
Name: woning, dtype: int64

In [6]:
df_dummy['horeca'] = (df_dummy['function'].isin(["Restaurant", "Horeca", "Hotel/motel", "Cafe/bar/restaurant", 
                                                    "Restaurant|Opslag/magazijn", "Hotelkamer", "Cafe/bar", "Cafetaria", 
                                                    "Restaurant|Keuken", "Cafe/bar|Opslag/magazijn", "Restaurant|Opslag/magazijn|Keuken", 
                                                    "Cafetaria|Opslag/magazijn", "Kantoor|Restaurant|Opslag/magazijn", 
                                                    "Restaurant|Sanitaire ruimte|Opslag/magazijn|Keuken", "Zaal (horeca)", 
                                                    "Woning + horeca", "Hotelkamer|Entree/garderobe"]))
df_dummy['horeca'] = list(map(int, df_dummy['horeca']))
df_dummy['horeca'].value_counts()

0    185904
1      2904
Name: horeca, dtype: int64

In [7]:
df_dummy['winkel'] = (df_dummy['function'].isin(["Winkel/verkoopruimte", "(Detail)handel/winkel", "Winkel/verkoopruimte|Opslag/magazijn", 
                                                 "Winkel", "Winkel/verkoopruimte|Kantoor|Opslag/magazijn", "Winkel/verkoopruimte|Kantoor",
                                                 "Winkel/verkoopruimte|Werkruimte", "Woning + (detail)handel/winkel", 
                                                 "Winkel/verkoopruimte|Kantine|Opslag/magazijn", "Winkel/verkoopruimte|Opslag/magazijn|Dagverblijf", 
                                                 "Winkel/verkoopruimte|Dagverblijf", "Woning|Winkel/verkoopruimte|Opslag/magazijn", 
                                                 "Woning|Winkel/verkoopruimte", "Woning in niet-woning|Winkel/verkoopruimte"]))
df_dummy['winkel'] = list(map(int, df_dummy['winkel']))
df_dummy['winkel'].value_counts()

0    182645
1      6163
Name: winkel, dtype: int64

In [8]:
df_dummy['bedrijf_en_kantoor'] = (df_dummy['function'].isin(["Kantoor", "Bedrijf", "Overig bedrijf", "Kantoor in bedrijfsverzamelgebouw", 
                                                             "Kantoor|Opslag/magazijn", "Werkruimte", "Werkplaats", "Atelier", 
                                                             "Praktijkruimte", "Kantoor|Werkruimte", "Atelier/werkruimte", 
                                                             "Winkel/verkoopruimte|Kantoor|Opslag/magazijn", 
                                                             "Winkel/verkoopruimte|Kantoor", "Opslag/magazijn|Werkplaats", 
                                                             "Opslag/magazijn|Praktijkruimte", "Kantoor|Opslag/magazijn|Werkplaats", 
                                                             "Kantoor|Sanitaire ruimte", "Kantoor|Technische installatieruimte", 
                                                             "Kantoor|Opslag/magazijn|Werkruimte", "Kantoor|Restaurant|Opslag/magazijn", 
                                                             "Kantoor|Entree/garderobe|Opslag/magazijn", "Productieruimte", "Kantoor|Productieruimte", 
                                                             "Parkeerplaats|Kantoor|Opslag/magazijn", "Kantoor|Opslag/magazijn|Overige ruimten", 
                                                             "Woning|Kantoor"]))
df_dummy['bedrijf_en_kantoor'] = list(map(int, df_dummy['bedrijf_en_kantoor']))
df_dummy['bedrijf_en_kantoor'].value_counts()

0    178024
1     10784
Name: bedrijf_en_kantoor, dtype: int64

In [9]:
df_dummy['kerk_en_gebedsruimte'] = (df_dummy['function'].isin(["Kerk", "Kerkzaal (gebedsruimte)"]))
df_dummy['kerk_en_gebedsruimte'] = list(map(int, df_dummy['kerk_en_gebedsruimte']))
df_dummy['kerk_en_gebedsruimte'].value_counts()

0    188732
1        76
Name: kerk_en_gebedsruimte, dtype: int64

In [10]:
df_dummy['bejaardenhuis_tehuis_en_bijzondere_woonfunctie'] = (df_dummy['function'].isin(["Verzorgings-/bejaardentehuis", 
                                                                             "Gezinsvervangend tehuis", "Bijzondere woonfunctie"]))
df_dummy['bejaardenhuis_tehuis_en_bijzondere_woonfunctie'] = list(map(int, df_dummy['bejaardenhuis_tehuis_en_bijzondere_woonfunctie']))
df_dummy['bejaardenhuis_tehuis_en_bijzondere_woonfunctie'].value_counts()

0    188496
1       312
Name: bejaardenhuis_tehuis_en_bijzondere_woonfunctie, dtype: int64

In [11]:
df_dummy['cultuur_en_musea'] = (df_dummy['function'].isin(["Cultuur", "Expositieruimte", "Museum"]))
df_dummy['cultuur_en_musea'] = list(map(int, df_dummy['cultuur_en_musea']))
df_dummy['cultuur_en_musea'].value_counts()

0    188629
1       179
Name: cultuur_en_musea, dtype: int64

In [12]:
df_dummy['medisch'] = (df_dummy['function'].isin(["Medisch", "Overig medisch"]))
df_dummy['medisch'] = list(map(int, df_dummy['medisch']))
df_dummy['medisch'].value_counts()

0    188768
1        40
Name: medisch, dtype: int64

In [13]:
df_dummy['kinderdagverblijf_en_basisschool'] = (df_dummy['function'].isin(["Creche", "Creche/peuterspeelzaal", 
                                                                           "Winkel/verkoopruimte|Opslag/magazijn|Dagverblijf", 
                                                                           "Winkel/verkoopruimte|Dagverblijf", "Basisschool"]))
df_dummy['kinderdagverblijf_en_basisschool'] = list(map(int, df_dummy['kinderdagverblijf_en_basisschool']))
df_dummy['kinderdagverblijf_en_basisschool'].value_counts()

0    188368
1       440
Name: kinderdagverblijf_en_basisschool, dtype: int64

In [14]:
df_dummy['middelbaar_en_speciaal_onderwijs'] = (df_dummy['function'].isin(["Algemeen voortgezet onderwijs (MAVO/HAVO/VWO)", 
                                                                           "Speciaal onderwijs"]))
df_dummy['middelbaar_en_speciaal_onderwijs'] = list(map(int, df_dummy['middelbaar_en_speciaal_onderwijs']))
df_dummy['middelbaar_en_speciaal_onderwijs'].value_counts()

0    188737
1        71
Name: middelbaar_en_speciaal_onderwijs, dtype: int64

In [15]:
df_dummy['beroeps_en_wetenschappelijk_onderwijs'] = (df_dummy['function'].isin(["Hogeschool/universiteit", 
                                                                                "Beroepsonderwijs (LBO/MBO)"]))
df_dummy['beroeps_en_wetenschappelijk_onderwijs'] = list(map(int, df_dummy['beroeps_en_wetenschappelijk_onderwijs']))
df_dummy['beroeps_en_wetenschappelijk_onderwijs'].value_counts()

0    188737
1        71
Name: beroeps_en_wetenschappelijk_onderwijs, dtype: int64

In [16]:
df_dummy['garage_en_parkeerplaats'] = (df_dummy['function'].isin(["Garage", "Parkeerplaats", "Woning|Inpandige garage", 
                                                                  "Onderpandige garage", "Woning|Dakterras|Inpandige garage",
                                                                  "Parkeergarage geexploiteerd voor kortparkeren", 
                                                                  "Woning|Garage", "Parkeerplaats (niet dienstbaar wonen)", 
                                                                  "Woning|Berging/schuur|Parkeerplaats", "Woning|Onderpandige garage", 
                                                                  "Woning|Garage aangebouwd", "Woning|Garage|Berging/schuur", 
                                                                  "Woning|Balkon|Berging/schuur onderpandig|Parkeerplaats", 
                                                                  "Parkeerplaats|Kantoor|Opslag/magazijn", "Woning|Parkeerplaats", 
                                                                  "Onderpandige garage|Parkeerplaats", "Woning|Balkon|Parkeerplaats", 
                                                                  "Woning|Inpandige garage|Berging/schuur", "Woning|Balkon|Parkeerplaats", 
                                                                  "Woning|Dakterras|Garage aangebouwd", "Woning|Balkon|Inpandige garage"]))
df_dummy['garage_en_parkeerplaats'] = list(map(int, df_dummy['garage_en_parkeerplaats']))
df_dummy['garage_en_parkeerplaats'].value_counts()

0    185445
1      3363
Name: garage_en_parkeerplaats, dtype: int64

In [17]:
df_dummy['nr_of_rent'] = (df_dummy['ownership'] == "Huur")
df_dummy['nr_of_rent'] = list(map(int, df_dummy['nr_of_rent']))
df_dummy['nr_of_rent'].value_counts()

1    122169
0     66639
Name: nr_of_rent, dtype: int64

In [18]:
df_dummy['nr_of_possession'] = (df_dummy['ownership'] == "Eigendom")
df_dummy['nr_of_possession'] = list(map(int, df_dummy['nr_of_possession']))
df_dummy['nr_of_possession'].value_counts()

0    147621
1     41187
Name: nr_of_possession, dtype: int64

In [19]:
df_dummy['nr_of_tussengebouw'] = (df_dummy['situation'] == "Tussengebouw")
df_dummy['nr_of_tussengebouw'] = list(map(int, df_dummy['nr_of_tussengebouw']))
df_dummy['nr_of_tussengebouw'].value_counts()

0    104248
1     84560
Name: nr_of_tussengebouw, dtype: int64

In [20]:
df_dummy['nr_of_hoekgebouw'] = (df_dummy['situation'] == "Hoekgebouw")
df_dummy['nr_of_hoekgebouw'] = list(map(int, df_dummy['nr_of_hoekgebouw']))
df_dummy['nr_of_hoekgebouw'].value_counts()

0    134746
1     54062
Name: nr_of_hoekgebouw, dtype: int64

In [21]:
df_dummy['nr_of_vrijstaandgebouw'] = (df_dummy['situation'] == "Vrijstaand gebouw")
df_dummy['nr_of_vrijstaandgebouw'] = list(map(int, df_dummy['nr_of_vrijstaandgebouw']))
df_dummy['nr_of_vrijstaandgebouw'].value_counts()

0    161563
1     27245
Name: nr_of_vrijstaandgebouw, dtype: int64

In [22]:
df_dummy['nr_of_half_vrijstaandgebouw'] = (df_dummy['situation'] == "Half vrijstaand gebouw")
df_dummy['nr_of_half_vrijstaandgebouw'] = list(map(int, df_dummy['nr_of_half_vrijstaandgebouw']))
df_dummy['nr_of_half_vrijstaandgebouw'].value_counts()

0    187001
1      1807
Name: nr_of_half_vrijstaandgebouw, dtype: int64

In [23]:
df_dummy['nr_of_situation_anders'] = (df_dummy['situation'] == "Anders")
df_dummy['nr_of_situation_anders'] = list(map(int, df_dummy['nr_of_situation_anders']))
df_dummy['nr_of_situation_anders'].value_counts()

0    173115
1     15693
Name: nr_of_situation_anders, dtype: int64

In [24]:
df_dummy['nr_of_kopgebouw'] = (df_dummy['situation'] == "Kopgebouw")
df_dummy['nr_of_kopgebouw'] = list(map(int, df_dummy['nr_of_kopgebouw']))
df_dummy['nr_of_kopgebouw'].value_counts()

0    187766
1      1042
Name: nr_of_kopgebouw, dtype: int64

In [25]:
df_dummy

,object_id,incident,nr_of_accomodations_in_building,nr_of_residential_accomodations_in_building,floorsize_accomodation,construction_year,timeline,function,situation,ownership,...,beroeps_en_wetenschappelijk_onderwijs,garage_en_parkeerplaats,nr_of_rent,nr_of_possession,nr_of_tussengebouw,nr_of_hoekgebouw,nr_of_vrijstaandgebouw,nr_of_half_vrijstaandgebouw,nr_of_situation_anders,nr_of_kopgebouw
0,1b47f57e7692d3c095345d98bfd85b1c06dd9c268d5dd4...,0,15,13,29,983,31/12/9999,Woning|Berging/schuur,Tussengebouw,Huur,...,0,0,1,0,1,0,0,0,0,0
1,1b47f57e7692d3c095345d98bfd85b1c06dd9c268d5dd4...,0,14,4,19,983,31/12/9999,Woning|Berging/schuur,Tussengebouw,Huur,...,0,0,1,0,1,0,0,0,0,0
2,4db936db50deabc74a224621503fc16465e29f23fcb595...,0,10,8,51,983,31/12/9999,Woning|Berging/schuur,Tussengebouw,Huur,...,0,0,1,0,1,0,0,0,0,0
3,4db936db50deabc74a224621503fc16465e29f23fcb595...,0,15,3,36,983,31/12/9999,Woning|Berging/schuur,Tussengebouw,Huur,...,0,0,1,0,1,0,0,0,0,0
4,4db936db50deabc74a224621503fc16465e29f23fcb595...,0,10,8,18,983,18/06/2012,Woning,Tussengebouw,Huur,...,0,0,1,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188803,82dc2820e82c5b79e6876209e83c802ac36fbf8d72b5f1...,0,4,0,415,1836,31/12/9999,Kantoor|Opslag/magazijn,Vrijstaand gebouw,Huur,...,0,0,1,0,0,0,1,0,0,0
188804,91d8b28b71969b077b037223083a833f95d2f0a0e3c75e...,0,4,1,1507,1615,31/12/9999,Kantoor,Tussengebouw,Eigendom,...,0,0,0,1,1,0,0,0,0,0
188805,1f44551055c236017d222f45189196ba7ab2bd2a0c38f7...,0,4,3,22194,1618,31/12/9999,Overige ruimten,Vrijstaand gebouw,Huur,...,0,0,1,0,0,0,1,0,0,0
188806,f7897f3ba448a860eb0ee2909324d5dd5e20b1e863bd03...,0,26,25,36,1712,09/08/2013,Woning,Tussengebouw,Huur,...,0,0,1,0,1,0,0,0,0,0
188807,f7897f3ba448a860eb0ee2909324d5dd5e20b1e863bd03...,0,22,10,25,1712,31/12/9999,Woning,Tussengebouw,Huur,...,0,0,1,0,1,0,0,0,0,0

In [26]:
df_dummy = df_dummy[['neighborhood', 'woning', 'horeca', 'winkel', 'bedrijf_en_kantoor', 'kerk_en_gebedsruimte',
                     'cultuur_en_musea', 'medisch', 'bejaardenhuis_tehuis_en_bijzondere_woonfunctie', 
                     'kinderdagverblijf_en_basisschool', 'middelbaar_en_speciaal_onderwijs', 'beroeps_en_wetenschappelijk_onderwijs', 
                     'garage_en_parkeerplaats', 'nr_of_rent', 'nr_of_possession', 
                     'construction_year', 'timeline', 'nr_of_tussengebouw', 'nr_of_hoekgebouw', 'nr_of_vrijstaandgebouw', 
                     'nr_of_half_vrijstaandgebouw', 'nr_of_kopgebouw', 'nr_of_situation_anders', 
                     'nr_of_accomodations_in_building', 'nr_of_residential_accomodations_in_building', 
                     'floorsize_accomodation', 'incident', 'is_monument', 'nr_of_inspections_within_timeline', 
                     'nr_of_inspections_with_observation', 'nr_of_inspections_without_observation']]

In [27]:
df_dummy = df_dummy.replace({'Overtoomse veld Zuid':'Overtoomse Veld Zuid', 'Rai':'RAI', 
                             'Zuidwestkadrant Indische buurt':'Zuidwestkwadrant Indische buurt', 
                             'BelgiÃƒÂ«plein e.o.':'Belgieplein e.o.', 
                             'Jacques Veldmanbuurt':'Jacques Veltmanbuurt', 'de Plantage':'De Plantage', 
                             'Pieter van Doesburgbuurt':'Pieter van der Doesbuurt', 'Nintermanterrein':'Nintemanterrein'})
df_dummy = df_dummy.groupby(['neighborhood'], as_index = False).agg({'woning':'sum',
                                                                     'horeca':'sum', 
                                                                     'winkel':'sum', 
                                                                     'bedrijf_en_kantoor':'sum', 
                                                                     'kerk_en_gebedsruimte':'sum',
                                                                     'cultuur_en_musea':'sum', 
                                                                     'medisch':'sum', 
                                                                     'bejaardenhuis_tehuis_en_bijzondere_woonfunctie':'sum', 
                                                                     'kinderdagverblijf_en_basisschool':'sum', 
                                                                     'middelbaar_en_speciaal_onderwijs':'sum', 
                                                                     'beroeps_en_wetenschappelijk_onderwijs':'sum', 
                                                                     'garage_en_parkeerplaats':'sum', 
                                                                     'nr_of_rent':'sum', 
                                                                     'nr_of_possession':'sum', 
                                                                     'construction_year':'mean',
                                                                     'timeline':'max', 
                                                                     'nr_of_tussengebouw':'sum', 
                                                                     'nr_of_hoekgebouw':'sum', 
                                                                     'nr_of_vrijstaandgebouw':'sum', 
                                                                     'nr_of_half_vrijstaandgebouw':'sum', 
                                                                     'nr_of_kopgebouw':'sum', 
                                                                     'nr_of_situation_anders':'sum', 
                                                                     'nr_of_accomodations_in_building':'mean', 
                                                                     'nr_of_residential_accomodations_in_building':'mean', 
                                                                     'floorsize_accomodation':'mean', 
                                                                     'is_monument':'sum',
                                                                     'incident':'sum',
                                                                     'nr_of_inspections_within_timeline':'sum', 
                                                                     'nr_of_inspections_with_observation':'sum', 
                                                                     'nr_of_inspections_without_observation':'sum'}).round(0)
df_dummy = df_dummy.rename(columns = {'construction_year':'avg_construction_year', 'timeline':'time_of_change', 
                                     'nr_of_accomodations_in_building':'avg_nr_of_accomodations_in_building', 
                                     'nr_of_residential_accomodations_in_building':'avg_nr_of_res_accomodations_in_building', 
                                     'is_monument':'nr_of_monuments'})
df_dummy[['avg_construction_year', 'avg_nr_of_accomodations_in_building', 'avg_nr_of_res_accomodations_in_building', 
          'floorsize_accomodation']] = df_dummy[['avg_construction_year', 'avg_nr_of_accomodations_in_building', 
                             'avg_nr_of_res_accomodations_in_building', 'floorsize_accomodation']].astype(int)
df_dummy

,neighborhood,woning,horeca,winkel,bedrijf_en_kantoor,kerk_en_gebedsruimte,cultuur_en_musea,medisch,bejaardenhuis_tehuis_en_bijzondere_woonfunctie,kinderdagverblijf_en_basisschool,...,nr_of_kopgebouw,nr_of_situation_anders,avg_nr_of_accomodations_in_building,avg_nr_of_res_accomodations_in_building,floorsize_accomodation,nr_of_monuments,incident,nr_of_inspections_within_timeline,nr_of_inspections_with_observation,nr_of_inspections_without_observation
0,AMC,0,0,0,1,0,0,0,0,0,...,0,0,3,1,128,0,1,0,0,0
1,Aalsmeerwegbuurt Oost,325,2,23,5,0,0,0,0,2,...,0,0,10,5,76,0,5,11,1,10
2,Aalsmeerwegbuurt West,398,4,3,1,0,0,0,0,2,...,0,3,7,3,72,0,1,5,1,4
3,Aetsveld Noord,37,0,1,1,0,0,0,0,0,...,0,0,9,4,117,0,0,0,0,0
4,Aetsveld Zuid,42,0,0,0,0,0,0,0,0,...,0,0,5,2,78,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,Zuidwestkwadrant Indische buurt,1610,4,8,48,0,0,0,0,2,...,0,38,28,15,81,48,8,0,0,0
516,Zuidwestkwadrant Osdorp Noord,502,0,18,8,0,0,0,0,1,...,0,37,59,29,101,0,7,0,0,0
517,Zuidwestkwadrant Osdorp Zuid,1118,8,26,35,0,0,0,0,0,...,0,190,89,45,101,0,12,0,0,0
518,Zunderdorp,24,0,0,1,0,0,0,0,3,...,0,4,4,2,153,0,0,29,4,25
519,Zwarte Gouw,1,0,0,0,0,0,0,0,0,...,0,0,13,4,37,0,0,0,0,0

In [28]:
df_dummy.dtypes

neighborhood                                      object
woning                                             int64
horeca                                             int64
winkel                                             int64
bedrijf_en_kantoor                                 int64
kerk_en_gebedsruimte                               int64
cultuur_en_musea                                   int64
medisch                                            int64
bejaardenhuis_tehuis_en_bijzondere_woonfunctie     int64
kinderdagverblijf_en_basisschool                   int64
middelbaar_en_speciaal_onderwijs                   int64
beroeps_en_wetenschappelijk_onderwijs              int64
garage_en_parkeerplaats                            int64
nr_of_rent                                         int64
nr_of_possession                                   int64
avg_construction_year                              int32
time_of_change                                    object
nr_of_tussengebouw                                 int64
nr_of_hoekgebouw                                   int64
nr_of_vrijstaandgebouw                             int64
nr_of_half_vrijstaandgebouw                        int64
nr_of_kopgebouw                                    int64
nr_of_situation_anders                             int64
avg_nr_of_accomodations_in_building                int32
avg_nr_of_res_accomodations_in_building            int32
floorsize_accomodation                             int32
nr_of_monuments                                    int64
incident                                           int64
nr_of_inspections_within_timeline                  int64
nr_of_inspections_with_observation                 int64
nr_of_inspections_without_observation              int64
dtype: object

In [29]:
df_dummy.to_csv('dummy_def_neighborhood_V2.csv')