In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [34]:
df_age = pd.read_csv('buurt_leeftijd_bevolkingsdichtheid.csv', index_col=0)
df_building_year = pd.read_csv('buurt_bouwjaar.csv', index_col=0)
df_dummy = pd.read_csv('dummy_def_neighborhood_V2.csv', index_col=0)

In [35]:
df_age

,BuurtCode,BuurtNaam,InwonersTotaal,Leeftijd 0-15,% Leeftijd 0-15,Leeftijd 65+,% Leeftijd 65+,GemiddeldeHuishoudensgrootte,Bevolkingsdichtheid
2,BU03630000,Kop Zeedijk,1110,45,4.054054,100,9.009009,1.4,18349
3,BU03630001,Oude Kerk e.o.,695,20,2.877698,70,10.071942,1.4,7910
4,BU03630002,Burgwallen Oost,1645,90,5.471125,180,10.942249,1.4,26460
5,BU03630003,Nes e.o.,365,25,6.849315,30,8.219178,1.5,6883
6,BU03630004,BG-terrein e.o.,690,40,5.797101,80,11.594203,1.4,8161
...,...,...,...,...,...,...,...,...,...
573,BU03639701,Gein Zuidwest,1665,310,18.618619,125,7.507508,1.9,9544
574,BU03639702,Gein Noordoost,3245,450,13.867488,660,20.338983,2.3,5109
575,BU03639703,Gein Zuidoost,3355,510,15.201192,630,18.777943,2.0,4676
577,BU03639800,Dorp Driemond,1480,265,17.905405,275,18.581081,2.3,5099
578,BU03639801,Landelijk gebied Driemond,140,45,32.142857,10,7.142857,3.5,98

In [36]:
df_building_year.rename(columns={'Wijken en buurten' : 'BuurtNaam'}, inplace=True)
df_building_year = df_building_year.replace('.', np.NaN)

df_building_year

                     BuurtNaam Bouwjaar voor 2000 Bouwjaar vanaf 2000
1                  Kop Zeedijk                 96                   4
2               Oude Kerk e.o.                 87                  13
3              Burgwallen Oost                 96                   4
4                     Nes e.o.                 98                   2
5              BG-terrein e.o.                100                   0
..                         ...                ...                 ...
572              Gein Zuidwest                100                   0
573             Gein Noordoost                100                   0
574              Gein Zuidoost                100                   0
576              Dorp Driemond                 94                   6
577  Landelijk gebied Driemond                 32                  68

[475 rows x 3 columns]

In [37]:
df_dummy.rename(columns={'neighborhood' : 'BuurtNaam'}, inplace=True)
df_dummy

,BuurtNaam,woning,horeca,winkel,bedrijf_en_kantoor,kerk_en_gebedsruimte,cultuur_en_musea,medisch,bejaardenhuis_tehuis_en_bijzondere_woonfunctie,kinderdagverblijf_en_basisschool,...,nr_of_kopgebouw,nr_of_situation_anders,avg_nr_of_accomodations_in_building,avg_nr_of_res_accomodations_in_building,floorsize_accomodation,nr_of_monuments,incident,nr_of_inspections_within_timeline,nr_of_inspections_with_observation,nr_of_inspections_without_observation
0,AMC,0,0,0,1,0,0,0,0,0,...,0,0,3,1,128,0,1,0,0,0
1,Aalsmeerwegbuurt Oost,325,2,23,5,0,0,0,0,2,...,0,0,10,5,76,0,5,11,1,10
2,Aalsmeerwegbuurt West,398,4,3,1,0,0,0,0,2,...,0,3,7,3,72,0,1,5,1,4
3,Aetsveld Noord,37,0,1,1,0,0,0,0,0,...,0,0,9,4,117,0,0,0,0,0
4,Aetsveld Zuid,42,0,0,0,0,0,0,0,0,...,0,0,5,2,78,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,Zuidwestkwadrant Indische buurt,1610,4,8,48,0,0,0,0,2,...,0,38,28,15,81,48,8,0,0,0
516,Zuidwestkwadrant Osdorp Noord,502,0,18,8,0,0,0,0,1,...,0,37,59,29,101,0,7,0,0,0
517,Zuidwestkwadrant Osdorp Zuid,1118,8,26,35,0,0,0,0,0,...,0,190,89,45,101,0,12,0,0,0
518,Zunderdorp,24,0,0,1,0,0,0,0,3,...,0,4,4,2,153,0,0,29,4,25
519,Zwarte Gouw,1,0,0,0,0,0,0,0,0,...,0,0,13,4,37,0,0,0,0,0

In [38]:
df_all_features = pd.merge(df_age, df_building_year, how='outer', on='BuurtNaam')
df_all_features

,BuurtCode,BuurtNaam,InwonersTotaal,Leeftijd 0-15,% Leeftijd 0-15,Leeftijd 65+,% Leeftijd 65+,GemiddeldeHuishoudensgrootte,Bevolkingsdichtheid,Bouwjaar voor 2000,Bouwjaar vanaf 2000
0,BU03630000,Kop Zeedijk,1110.0,45.0,4.054054,100.0,9.009009,1.4,18349,96,4
1,BU03630001,Oude Kerk e.o.,695.0,20.0,2.877698,70.0,10.071942,1.4,7910,87,13
2,BU03630002,Burgwallen Oost,1645.0,90.0,5.471125,180.0,10.942249,1.4,26460,96,4
3,BU03630003,Nes e.o.,365.0,25.0,6.849315,30.0,8.219178,1.5,6883,98,2
4,BU03630004,BG-terrein e.o.,690.0,40.0,5.797101,80.0,11.594203,1.4,8161,100,0
...,...,...,...,...,...,...,...,...,...,...,...
476,BU03639703,Gein Zuidoost,3355.0,510.0,15.201192,630.0,18.777943,2.0,4676,100,0
477,BU03639800,Dorp Driemond,1480.0,265.0,17.905405,275.0,18.581081,2.3,5099,94,6
478,BU03639801,Landelijk gebied Driemond,140.0,45.0,32.142857,10.0,7.142857,3.5,98,32,68
479,NaN,ChassÃ©buurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90,10
480,NaN,BelgiÃ«plein e.o.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100,0

In [39]:
df_all_features = pd.merge(df_all_features, df_dummy, how='outer', on='BuurtNaam')
df_all_features

,BuurtCode,BuurtNaam,InwonersTotaal,Leeftijd 0-15,% Leeftijd 0-15,Leeftijd 65+,% Leeftijd 65+,GemiddeldeHuishoudensgrootte,Bevolkingsdichtheid,Bouwjaar voor 2000,...,nr_of_kopgebouw,nr_of_situation_anders,avg_nr_of_accomodations_in_building,avg_nr_of_res_accomodations_in_building,floorsize_accomodation,nr_of_monuments,incident,nr_of_inspections_within_timeline,nr_of_inspections_with_observation,nr_of_inspections_without_observation
0,BU03630000,Kop Zeedijk,1110.0,45.0,4.054054,100.0,9.009009,1.4,18349,96,...,0.0,56.0,11.0,5.0,1716.0,20.0,3.0,51.0,27.0,24.0
1,BU03630001,Oude Kerk e.o.,695.0,20.0,2.877698,70.0,10.071942,1.4,7910,87,...,0.0,61.0,17.0,8.0,117.0,23.0,8.0,107.0,55.0,52.0
2,BU03630002,Burgwallen Oost,1645.0,90.0,5.471125,180.0,10.942249,1.4,26460,96,...,0.0,18.0,9.0,4.0,86.0,12.0,8.0,56.0,26.0,30.0
3,BU03630003,Nes e.o.,365.0,25.0,6.849315,30.0,8.219178,1.5,6883,98,...,1.0,5.0,8.0,4.0,442.0,69.0,5.0,73.0,40.0,33.0
4,BU03630004,BG-terrein e.o.,690.0,40.0,5.797101,80.0,11.594203,1.4,8161,100,...,0.0,2.0,10.0,5.0,680.0,32.0,3.0,95.0,50.0,45.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525,NaN,Staalmanpleinbuurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,26.0,32.0,15.0,121.0,21.0,6.0,0.0,0.0,0.0
526,NaN,Weespersluis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,8.0,5.0,184.0,0.0,0.0,0.0,0.0,0.0
527,NaN,Werengouw Noord,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,19.0,38.0,19.0,74.0,0.0,1.0,0.0,0.0,0.0
528,NaN,Zuid I Weesp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,12.0,5.0,79.0,0.0,0.0,0.0,0.0,0.0
529,NaN,Zuid II Weesp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,4.0,2.0,146.0,0.0,0.0,0.0,0.0,0.0

In [40]:
# Write to csv
df_all_features.to_csv('all_features.csv')