In [1]:
# Load the necessary libraries 
import datetime 
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
# Loading the bagadres-woning.csv set
df_kadaster = pd.read_csv('bagadres-woning.csv', delimiter = ';', index_col = False) 
df_kadaster = df_kadaster[df_kadaster['woonplaats'] == 'Amsterdam'].reset_index()
df_kadaster

C:\Users\richa\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3326: DtypeWarning: Columns (1,5,6) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,index,openbareruimtenaam,verkorteopenbareruimtenaam,openbareruimte_id,huisnummer,huisletter,huisnummertoevoeging,postcode,nummeraanduiding_id,buurtnaam,...,woningtype,omtrek_pand,verhouding_opp_vbo_opp_pnd,pandstatus,bouwjaar,uniq_key,pchnhlht,pchnhlht_uniek,pchn_uniek,rangorde_pchn
0,0,De Ruijterkade,NaN,363300000006091,105,NaN,1,1011AB,363200000081086,Oosterdokseiland,...,NaN,64.0,5.13,Pand in gebruik,1884.0,1011AB-105-0-1-0363300000006091,1011AB-105-0-1,1.0,0.0,3
1,1,De Ruijterkade,NaN,363300000006091,105,NaN,2,1011AB,363200000081087,Oosterdokseiland,...,Appartement,64.0,5.13,Pand in gebruik,1884.0,1011AB-105-0-2-0363300000006091,1011AB-105-0-2,1.0,0.0,1
2,2,De Ruijterkade,NaN,363300000006091,105,NaN,3,1011AB,363200000081088,Oosterdokseiland,...,Appartement,64.0,5.13,Pand in gebruik,1884.0,1011AB-105-0-3-0363300000006091,1011AB-105-0-3,1.0,0.0,2
3,3,De Ruijterkade,NaN,363300000006091,105,NaN,H,1011AB,363200000081085,Oosterdokseiland,...,NaN,64.0,5.13,Pand in gebruik,1884.0,1011AB-105-0-H-0363300000006091,1011AB-105-0-H,1.0,0.0,4
4,4,De Ruijterkade,NaN,363300000006091,106,NaN,1,1011AB,363200012064203,Oosterdokseiland,...,NaN,64.0,5.13,Pand in gebruik,1884.0,1011AB-106-0-1-0363300000006091,1011AB-106-0-1,1.0,0.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539586,9521019,tt. Vasumweg,NaN,363300000005872,34,E,NaN,NaN,363200012171816,NDSM terrein,...,NaN,370.0,9.89,Bouw gestart,2018.0,0-34-E-0-0363300000005872,0-34-E-0,NaN,NaN,863
539587,9521020,tt. Vasumweg,NaN,363300000005872,38,B,NaN,NaN,363200012141995,NDSM terrein,...,NaN,370.0,9.89,Bouw gestart,2018.0,0-38-B-0-0363300000005872,0-38-B-0,NaN,NaN,814
539588,9521021,tt. Vasumweg,NaN,363300000005872,38,C,NaN,NaN,363200012141994,NDSM terrein,...,NaN,370.0,9.89,Bouw gestart,2018.0,0-38-C-0-0363300000005872,0-38-C-0,NaN,NaN,834
539589,9521022,tt. Vasumweg,NaN,363300000005872,38,D,NaN,NaN,363200012141993,NDSM terrein,...,NaN,370.0,9.89,Bouw gestart,2018.0,0-38-D-0-0363300000005872,0-38-D-0,NaN,NaN,849
539590,9521023,tt. Vasumweg,NaN,363300000005872,69,NaN,NaN,NaN,363200012104257,NDSM terrein,...,NaN,289.0,1.21,Pand in gebruik,2019.0,0-69-0-0-0363300000005872,0-69-0-0,NaN,NaN,87

In [3]:
df_kadaster.drop(['verkorteopenbareruimtenaam', 'openbareruimte_id', 'nummeraanduiding_id', 'woonplaatscode', 'gemeente', 
                  'provincienaam', 'provinciecode', 'uniq_key', 'pchnhlht', 'pchnhlht_uniek', 'pchn_uniek', 'rangorde_pchn'], 
                 axis=1, inplace=True)
df_kadaster

,index,openbareruimtenaam,huisnummer,huisletter,huisnummertoevoeging,postcode,buurtnaam,buurtcode,wijknaam,wijkcode,...,aantal_pand_relaties_dit_vbo,pand_id,aantal_vbo_relaties_dit_pnd,vbo_pnd_1_op_1,opp_pand,woningtype,omtrek_pand,verhouding_opp_vbo_opp_pnd,pandstatus,bouwjaar
0,0,De Ruijterkade,105,NaN,1,1011AB,Oosterdokseiland,BU03630400,Nieuwmarkt/Lastage,WK036304,...,1.0,3.631000e+14,8.0,0.0,228.0,NaN,64.0,5.13,Pand in gebruik,1884.0
1,1,De Ruijterkade,105,NaN,2,1011AB,Oosterdokseiland,BU03630400,Nieuwmarkt/Lastage,WK036304,...,1.0,3.631000e+14,8.0,0.0,228.0,Appartement,64.0,5.13,Pand in gebruik,1884.0
2,2,De Ruijterkade,105,NaN,3,1011AB,Oosterdokseiland,BU03630400,Nieuwmarkt/Lastage,WK036304,...,1.0,3.631000e+14,8.0,0.0,228.0,Appartement,64.0,5.13,Pand in gebruik,1884.0
3,3,De Ruijterkade,105,NaN,H,1011AB,Oosterdokseiland,BU03630400,Nieuwmarkt/Lastage,WK036304,...,1.0,3.631000e+14,8.0,0.0,228.0,NaN,64.0,5.13,Pand in gebruik,1884.0
4,4,De Ruijterkade,106,NaN,1,1011AB,Oosterdokseiland,BU03630400,Nieuwmarkt/Lastage,WK036304,...,1.0,3.631000e+14,8.0,0.0,228.0,NaN,64.0,5.13,Pand in gebruik,1884.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539586,9521019,tt. Vasumweg,34,E,NaN,NaN,NDSM terrein,BU03637105,Noordelijke IJ-oevers West,WK036371,...,1.0,3.631000e+14,460.0,0.0,3614.0,NaN,370.0,9.89,Bouw gestart,2018.0
539587,9521020,tt. Vasumweg,38,B,NaN,NaN,NDSM terrein,BU03637105,Noordelijke IJ-oevers West,WK036371,...,1.0,3.631000e+14,460.0,0.0,3614.0,NaN,370.0,9.89,Bouw gestart,2018.0
539588,9521021,tt. Vasumweg,38,C,NaN,NaN,NDSM terrein,BU03637105,Noordelijke IJ-oevers West,WK036371,...,1.0,3.631000e+14,460.0,0.0,3614.0,NaN,370.0,9.89,Bouw gestart,2018.0
539589,9521022,tt. Vasumweg,38,D,NaN,NaN,NDSM terrein,BU03637105,Noordelijke IJ-oevers West,WK036371,...,1.0,3.631000e+14,460.0,0.0,3614.0,NaN,370.0,9.89,Bouw gestart,2018.0
539590,9521023,tt. Vasumweg,69,NaN,NaN,NaN,NDSM terrein,BU03637105,Noordelijke IJ-oevers West,WK036371,...,1.0,3.631000e+14,4.0,0.0,3435.0,NaN,289.0,1.21,Pand in gebruik,2019.0

In [4]:
df_kadaster['potent_pand_asbest'] = ((df_kadaster['bouwjaar'] >= 1955) & (df_kadaster['bouwjaar'] <= 1978))
df_kadaster['potent_pand_asbest'] = list(map(int, df_kadaster['potent_pand_asbest']))

# 1 = potential cases of asbest and 0 = no asbest
print(df_kadaster['potent_pand_asbest'].value_counts())

0    453839
1     85752
Name: potent_pand_asbest, dtype: int64

In [5]:
df_kadaster.dtypes

index                             int64
openbareruimtenaam               object
huisnummer                        int64
huisletter                       object
huisnummertoevoeging             object
postcode                         object
buurtnaam                        object
buurtcode                        object
wijknaam                         object
wijkcode                         object
woonplaats                       object
gemeentecode                      int64
nevenadres                        int64
typeadresseerbaarobject          object
adresseerbaarobject_status       object
opp_adresseerbaarobject_m2        int64
aantal_nad_per_adresobject        int64
adresseerbaarobject_id            int64
x                               float64
y                               float64
lon                             float64
lat                             float64
woonfunctie                     float64
bijeenkomstfunctie              float64
celfunctie                      float64
gezondheidszorgfunctie          float64
industriefunctie                float64
kantoorfunctie                  float64
logiesfunctie                   float64
onderwijsfunctie                float64
sportfunctie                    float64
winkelfunctie                   float64
overige_gebruiksfunctie         float64
aantal_pand_relaties_dit_vbo    float64
pand_id                         float64
aantal_vbo_relaties_dit_pnd     float64
vbo_pnd_1_op_1                  float64
opp_pand                        float64
woningtype                       object
omtrek_pand                     float64
verhouding_opp_vbo_opp_pnd      float64
pandstatus                       object
bouwjaar                        float64
potent_pand_asbest                int64
dtype: object

According to the research by Xin and Huan (2013, https://www.sciencedirect.com/science/article/pii/S0379711213001653), most fire occurences from 2007 to 2010 within China happened in "Residential buildings" (complete top 3 is also "Industry buildings" and "Public buildings", see table 3 of the linked paper). So the probability of fire is higher at residential buildings in comparison to the other two types.

In [6]:
# Load CSV from CBS (2020, https://www.cbs.nl/nl-nl/maatwerk/2020/33/energielevering-aan-woningen-en-bedrijven-naar-postcode)
df_energy = pd.read_csv('Publicatiefile_Energie_2020.csv', index_col = False, sep = ';')

# Clean up
df_energy = df_energy.rename(columns = {"Postcode6":"postcode", "Gemiddelde_aardgaslevering_woningen":"gem_gas_woning", 
                                        "Gemiddelde_aardgaslevering_woningen_gecorrigeerd": "gem_gas_woning_cor", 
                                       "Gemiddelde_aardgaslevering_bedrijven":"gem_gas_bedrijf", 
                                        'Gemiddelde_elektriciteitslevering_woningen':'gem_elektriciteit_woning', 
                                        'Gemiddelde_elektriciteitslevering_bedrijven':'gem_elektriciteit_bedrijf'})
df_energy = df_energy.replace('.', 0)
df_energy[["gem_gas_woning", "gem_gas_woning_cor", "gem_gas_bedrijf", 
           "gem_elektriciteit_woning", "gem_elektriciteit_bedrijf"]] = df_energy[["gem_gas_woning", "gem_gas_woning_cor", 
                                                                                  "gem_gas_bedrijf", "gem_elektriciteit_woning", 
                                                                                  "gem_elektriciteit_bedrijf"]].astype(str).astype(int)
df_energy

,postcode,gem_gas_woning,gem_gas_woning_cor,gem_elektriciteit_woning,gem_gas_bedrijf,gem_elektriciteit_bedrijf
0,1011AB,0,0,0,5930,62110
1,1011AC,1800,2090,2880,10410,68890
2,1011AD,0,0,0,0,971750
3,1011AE,0,0,0,0,0
4,1011AG,0,0,0,4700,32060
...,...,...,...,...,...,...
457493,9999XG,0,0,0,0,0
457494,9999XH,0,0,0,0,0
457495,9999XJ,1970,2290,3280,1340,13440
457496,9999XK,1600,1860,2270,0,0
457497,9999XL,1780,2070,3100,0,0

In [7]:
df_env = pd.merge(df_kadaster, df_energy, on = 'postcode')
df_env

,index,openbareruimtenaam,huisnummer,huisletter,huisnummertoevoeging,postcode,buurtnaam,buurtcode,wijknaam,wijkcode,...,omtrek_pand,verhouding_opp_vbo_opp_pnd,pandstatus,bouwjaar,potent_pand_asbest,gem_gas_woning,gem_gas_woning_cor,gem_elektriciteit_woning,gem_gas_bedrijf,gem_elektriciteit_bedrijf
0,0,De Ruijterkade,105,NaN,1,1011AB,Oosterdokseiland,BU03630400,Nieuwmarkt/Lastage,WK036304,...,64.0,5.13,Pand in gebruik,1884.0,0,0,0,0,5930,62110
1,1,De Ruijterkade,105,NaN,2,1011AB,Oosterdokseiland,BU03630400,Nieuwmarkt/Lastage,WK036304,...,64.0,5.13,Pand in gebruik,1884.0,0,0,0,0,5930,62110
2,2,De Ruijterkade,105,NaN,3,1011AB,Oosterdokseiland,BU03630400,Nieuwmarkt/Lastage,WK036304,...,64.0,5.13,Pand in gebruik,1884.0,0,0,0,0,5930,62110
3,3,De Ruijterkade,105,NaN,H,1011AB,Oosterdokseiland,BU03630400,Nieuwmarkt/Lastage,WK036304,...,64.0,5.13,Pand in gebruik,1884.0,0,0,0,0,5930,62110
4,4,De Ruijterkade,106,NaN,1,1011AB,Oosterdokseiland,BU03630400,Nieuwmarkt/Lastage,WK036304,...,64.0,5.13,Pand in gebruik,1884.0,0,0,0,0,5930,62110
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
527780,537385,Jaargetijden,1,NaN,NaN,1109CH,Dorp Driemond,BU03639800,Driemond,WK036398,...,36.0,2.28,Pand in gebruik,2010.0,0,0,0,0,0,0
527781,537386,Jaargetijden,3,NaN,NaN,1109CH,Dorp Driemond,BU03639800,Driemond,WK036398,...,25.0,1.18,Pand in gebruik,2014.0,0,0,0,0,0,0
527782,537387,Jaargetijden,5,NaN,NaN,1109CH,Dorp Driemond,BU03639800,Driemond,WK036398,...,15.0,1.85,Pand in gebruik,1989.0,0,0,0,0,0,0
527783,537388,Sluispad,4,NaN,NaN,1109CJ,Dorp Driemond,BU03639800,Driemond,WK036398,...,45.0,1.42,Pand in gebruik,1992.0,0,0,0,0,0,0
527784,537389,Sluispad,5,NaN,NaN,1109CJ,Dorp Driemond,BU03639800,Driemond,WK036398,...,57.0,1.60,Pand in gebruik,1992.0,0,0,0,0,0,0

In [8]:
def filter_by_freq(df: pd.DataFrame, column: str, min_freq: int) -> pd.DataFrame:
    """Filters df based on value frequency in specified column.
    
    Input: 
    df: dataframe to be filtered
    column: name column that should be frequency filtered
    min_freq: minimal value frequency for the row to be accepted
    
    Output:
    Frequency filtered dataframe
    
    """
    
    freq = df[column].value_counts()
    frequent_values = freq[freq >= min_freq].index
    return df[df[column].isin(frequent_values)]

In [9]:
df_env['gebouwen_gebruik_gas'] = ((df_env['gem_gas_woning_cor'] > 0) | (df_env['gem_gas_bedrijf'] > 0))
df_env['gebouwen_gebruik_gas'] = list(map(int, df_env['gebouwen_gebruik_gas']))

# 1 = building that uses gas and 0 = no gas usage
print(df_env['gebouwen_gebruik_gas'].value_counts())

1    450180
0     77605
Name: gebouwen_gebruik_gas, dtype: int64

In [10]:
woon_post = df_env[df_env['woonfunctie'] == 1]
woon_post = filter_by_freq(woon_post, 'postcode', 10) # 10 zipcodes is arbitrarily set 

df_env['meer_reg_woning'] = (df_env['postcode'].eq(woon_post['postcode']))
df_env['meer_reg_woning'] = list(map(int, df_env['meer_reg_woning']))

# 1 = Multiple woonfuncties located on same zipcode (equal or above 10), 0 = Everything below 10 registrations
print(df_env['meer_reg_woning'].value_counts())

1    465542
0     62243
Name: meer_reg_woning, dtype: int64

In [11]:
indu_post = df_env[df_env['industriefunctie'] == 1]
indu_post = filter_by_freq(indu_post, 'postcode', 2) # 2 zipcodes is arbitrarily set 

df_env['meer_reg_industrie'] = (df_env['postcode'].eq(indu_post['postcode']))
df_env['meer_reg_industrie'] = list(map(int, df_env['meer_reg_industrie']))

# 1 = Multiple industriefuncties on same zipcode (equal or above 2), 0 = Everything below 1 registrations
print(df_env['meer_reg_industrie'].value_counts())

0    519942
1      7843
Name: meer_reg_industrie, dtype: int64

In [12]:
df_env.dtypes

index                             int64
openbareruimtenaam               object
huisnummer                        int64
huisletter                       object
huisnummertoevoeging             object
postcode                         object
buurtnaam                        object
buurtcode                        object
wijknaam                         object
wijkcode                         object
woonplaats                       object
gemeentecode                      int64
nevenadres                        int64
typeadresseerbaarobject          object
adresseerbaarobject_status       object
opp_adresseerbaarobject_m2        int64
aantal_nad_per_adresobject        int64
adresseerbaarobject_id            int64
x                               float64
y                               float64
lon                             float64
lat                             float64
woonfunctie                     float64
bijeenkomstfunctie              float64
celfunctie                      float64
gezondheidszorgfunctie          float64
industriefunctie                float64
kantoorfunctie                  float64
logiesfunctie                   float64
onderwijsfunctie                float64
sportfunctie                    float64
winkelfunctie                   float64
overige_gebruiksfunctie         float64
aantal_pand_relaties_dit_vbo    float64
pand_id                         float64
aantal_vbo_relaties_dit_pnd     float64
vbo_pnd_1_op_1                  float64
opp_pand                        float64
woningtype                       object
omtrek_pand                     float64
verhouding_opp_vbo_opp_pnd      float64
pandstatus                       object
bouwjaar                        float64
potent_pand_asbest                int64
gem_gas_woning                    int32
gem_gas_woning_cor                int32
gem_elektriciteit_woning          int32
gem_gas_bedrijf                   int32
gem_elektriciteit_bedrijf         int32
gebouwen_gebruik_gas              int64
meer_reg_woning                   int64
meer_reg_industrie                int64
dtype: object

In [13]:
df_env = df_env[['buurtnaam', 'industriefunctie', 'sportfunctie', 'x', 'y', 'lon', 'lat', 
                 'gem_gas_woning', 'gem_gas_woning_cor', 'gem_elektriciteit_woning', 'gem_gas_bedrijf', 
                 'gem_elektriciteit_bedrijf', 'potent_pand_asbest', 'gebouwen_gebruik_gas', 'meer_reg_woning', 
                 'meer_reg_industrie']].rename(columns = {'industriefunctie':'industrie', 'sportfunctie':'sport'})
df_env

,buurtnaam,industrie,sport,x,y,lon,lat,gem_gas_woning,gem_gas_woning_cor,gem_elektriciteit_woning,gem_gas_bedrijf,gem_elektriciteit_bedrijf,potent_pand_asbest,gebouwen_gebruik_gas,meer_reg_woning,meer_reg_industrie
0,Oosterdokseiland,0.0,0.0,122177.000,487877.000,4.905167,52.377780,0,0,0,5930,62110,0,1,0,0
1,Oosterdokseiland,0.0,0.0,122177.000,487877.000,4.905167,52.377780,0,0,0,5930,62110,0,1,1,0
2,Oosterdokseiland,0.0,0.0,122177.000,487877.000,4.905167,52.377780,0,0,0,5930,62110,0,1,1,0
3,Oosterdokseiland,0.0,0.0,122177.000,487877.000,4.905167,52.377780,0,0,0,5930,62110,0,1,0,0
4,Oosterdokseiland,0.0,0.0,122185.000,487882.900,4.905284,52.377833,0,0,0,5930,62110,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
527780,Dorp Driemond,0.0,0.0,129848.593,479676.908,5.018442,52.304487,0,0,0,0,0,0,0,0,0
527781,Dorp Driemond,0.0,0.0,129827.096,479688.502,5.018126,52.304590,0,0,0,0,0,0,0,0,0
527782,Dorp Driemond,0.0,0.0,129833.000,479716.000,5.018210,52.304837,0,0,0,0,0,0,0,0,0
527783,Dorp Driemond,0.0,0.0,129902.000,479679.000,5.019224,52.304508,0,0,0,0,0,0,0,0,0
527784,Dorp Driemond,0.0,0.0,129916.000,479677.000,5.019430,52.304491,0,0,0,0,0,0,0,0,0

In [14]:
df_env = df_env.groupby(['buurtnaam'], as_index = False).agg({'industrie':'sum', 
                                                              'sport':'sum',
                                                              'x':'mean',
                                                              'y':'mean',
                                                              'lon':'mean',
                                                              'lat':'mean',
                                                              'gem_gas_woning':'mean',
                                                              'gem_gas_woning_cor':'mean',
                                                              'gem_elektriciteit_woning':'mean',
                                                              'gem_gas_bedrijf':'mean',
                                                              'gem_elektriciteit_bedrijf':'mean', 
                                                              'potent_pand_asbest':'sum', 
                                                              'gebouwen_gebruik_gas':'sum', 
                                                              'meer_reg_woning':'sum', 
                                                              'meer_reg_industrie':'sum'})
df_env

,buurtnaam,industrie,sport,x,y,lon,lat,gem_gas_woning,gem_gas_woning_cor,gem_elektriciteit_woning,gem_gas_bedrijf,gem_elektriciteit_bedrijf,potent_pand_asbest,gebouwen_gebruik_gas,meer_reg_woning,meer_reg_industrie
0,,0.0,0.0,127272.953985,486387.342103,4.980127,52.364672,30.016584,34.742952,2977.595357,0.000000,5753.349917,0,10,456,0
1,AMC,17.0,0.0,125675.148825,478351.402025,4.957369,52.292367,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,16
2,Aalsmeerwegbuurt Oost,8.0,0.0,118367.772758,484680.376785,4.849575,52.348810,891.599099,1035.645646,1963.205706,228.663664,4220.427928,0,1332,1276,4
3,Aalsmeerwegbuurt West,2.0,2.0,118227.640354,484799.733183,4.847506,52.349873,831.749175,965.504950,1888.567657,155.221122,1654.633663,0,1515,1471,0
4,Afrikahaven,84.0,1.0,111515.728019,491259.693721,4.748166,52.407439,0.000000,0.000000,0.000000,9377.115385,222510.000000,0,32,0,83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
472,Zuidwestkwadrant Osdorp Noord,9.0,0.0,114680.708515,485444.267917,4.795373,52.355417,710.314327,822.558480,2255.957602,128.830409,5753.333333,347,1363,1295,9
473,Zuidwestkwadrant Osdorp Zuid,6.0,0.0,114829.990130,484998.734523,4.797618,52.351424,692.016585,803.124764,2432.329438,444.078402,5690.995100,313,2576,2549,5
474,Zunderdorp,9.0,2.0,126429.346139,491425.694498,4.967313,52.409910,1461.082251,1696.233766,3432.164502,0.000000,7910.952381,58,225,182,7
475,Zwarte Gouw,0.0,0.0,127337.106000,488663.413294,4.980881,52.385132,818.823529,950.588235,1957.647059,0.000000,34936.470588,16,32,32,0
476,de Plantage,15.0,1.0,122698.904550,486568.549507,4.912957,52.366051,983.451552,1142.495250,2137.663078,3238.081064,22581.652945,12,1567,1415,7

In [15]:
df_env[['gem_gas_woning', 'gem_gas_woning_cor', 
        'gem_elektriciteit_woning', 'gem_gas_bedrijf', 'gem_elektriciteit_bedrijf']] = df_env[['gem_gas_woning', 'gem_gas_woning_cor', 
        'gem_elektriciteit_woning', 'gem_gas_bedrijf', 'gem_elektriciteit_bedrijf']].round(0)
df_env

,buurtnaam,industrie,sport,x,y,lon,lat,gem_gas_woning,gem_gas_woning_cor,gem_elektriciteit_woning,gem_gas_bedrijf,gem_elektriciteit_bedrijf,potent_pand_asbest,gebouwen_gebruik_gas,meer_reg_woning,meer_reg_industrie
0,,0.0,0.0,127272.953985,486387.342103,4.980127,52.364672,30.0,35.0,2978.0,0.0,5753.0,0,10,456,0
1,AMC,17.0,0.0,125675.148825,478351.402025,4.957369,52.292367,0.0,0.0,0.0,0.0,0.0,0,0,0,16
2,Aalsmeerwegbuurt Oost,8.0,0.0,118367.772758,484680.376785,4.849575,52.348810,892.0,1036.0,1963.0,229.0,4220.0,0,1332,1276,4
3,Aalsmeerwegbuurt West,2.0,2.0,118227.640354,484799.733183,4.847506,52.349873,832.0,966.0,1889.0,155.0,1655.0,0,1515,1471,0
4,Afrikahaven,84.0,1.0,111515.728019,491259.693721,4.748166,52.407439,0.0,0.0,0.0,9377.0,222510.0,0,32,0,83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
472,Zuidwestkwadrant Osdorp Noord,9.0,0.0,114680.708515,485444.267917,4.795373,52.355417,710.0,823.0,2256.0,129.0,5753.0,347,1363,1295,9
473,Zuidwestkwadrant Osdorp Zuid,6.0,0.0,114829.990130,484998.734523,4.797618,52.351424,692.0,803.0,2432.0,444.0,5691.0,313,2576,2549,5
474,Zunderdorp,9.0,2.0,126429.346139,491425.694498,4.967313,52.409910,1461.0,1696.0,3432.0,0.0,7911.0,58,225,182,7
475,Zwarte Gouw,0.0,0.0,127337.106000,488663.413294,4.980881,52.385132,819.0,951.0,1958.0,0.0,34936.0,16,32,32,0
476,de Plantage,15.0,1.0,122698.904550,486568.549507,4.912957,52.366051,983.0,1142.0,2138.0,3238.0,22582.0,12,1567,1415,7

In [16]:
df_env.dtypes

buurtnaam                     object
industrie                    float64
sport                        float64
x                            float64
y                            float64
lon                          float64
lat                          float64
gem_gas_woning               float64
gem_gas_woning_cor           float64
gem_elektriciteit_woning     float64
gem_gas_bedrijf              float64
gem_elektriciteit_bedrijf    float64
potent_pand_asbest             int64
gebouwen_gebruik_gas           int64
meer_reg_woning                int64
meer_reg_industrie             int64
dtype: object

$CO^2$ will be released when a fire occurs at buildings that uses gasses, so the environmental effect would be higher when that effect occurs. 

According to Martin, Tomida, and Meacham (2016, https://firesciencereviews.springeropen.com/articles/10.1186/s40038-016-0014-1), a combination of industrial buildings and gas usage, the environmental effects would be higher in comparison to the normal residential ones. It could also affect the waters when an industrial building is located near waters (release/leakage of chemicals). 

According to the fire deparment in the Netherlands (https://www.ifv.nl/kennisplein/Documents/20210321-BA-Jaaroverzicht-fatale-woningbranden-2020.pdf), the most common fires in the Netherlands (2020) were caused by equipment failure, smoking, cooking, playing with fire, and candles. 35% of them were classified as unknown, assuming that it is caused by people who have started a fire.  

We are only focusing on the air effect when a fire occurs, since the effect of ground is more applicable for the infrastructure effect, while the effect on water depends if there is an industry is located near the water. When that will result in a fire, then it will be leaking any chemicals in the water, but that is not the case in Amsterdam-Zuid. It becomes important when we are calculating the environmental effect in industrial areas which are located near waters, for example the industrial areas of Sloterdijk. 

*High gas usage* <br>
According to the CBS (2021, https://www.cbs.nl/nl-nl/cijfers/detail/81528NED), within Amsterdam, the average household uses 770 m3 of gas. When considering everything that is higher than 75% of 770 m3 (> 1155 m3), that is what we will classify as high usage neighborhoods. For the companies, it is unknown how much it is used, so the average of the CSV is used, which is 5090 m3. So 75% is equal to 7635 m3. 

*High asbest neighborhood* <br>
According to BAG data, there are 102.192 buildings build between 1950 and 1980. According to the information of the government (https://www.infomil.nl/onderwerpen/asbest/asbest-in-panden/), most houses between 1955 and 1978 contain a high amount of asbestos (https://www.infomil.nl/publish/pages/118796/rapport_asbest_in_kaart_tcm24-187269.pdf). So these buildings can be dangerous for the environment and for the people when a fire occurs. Asbestos was mostly applied in big buildings (flats, industrial areas, etc.). 

*Neighborhoods with more than one areas located on the same location (based on zipcode)* <br> 
Properties that are located near or at the same location that will contain fire while containing or uses gas could cause a high effect on a local level. Fumes of these fires could be dangerous for the environment and people in the neighborhood. 

*Neighborhoods with one or multiple industries* <br> 
When an industry has one (regional effect) or more than one industries (national effect when that catches fire) located that are working with (dangerous) chemicals, that can be dangerous for the environment in this case when a fire occurs. 

**Environmental Effects categorisation on neighborhood level** (based on the features that we have and literature) 
* *No/slight effect* (0-1): all buildings - high gas usage +/- year of build (homes build outside 1955-1978)
* *Minor effect* (2): all buildings (except for multiple homes/industrial buildings registered on same postcode) + high gas usage +/- year of build (homes build outside 1955-1978) 
* *Local effect* (3): multiple woonfuncties located on the same zipcode + high gas usage + year of build (homes build between 1955-1978)
* *Regional effect* (4): industrial buildings + high gas usage + year of build (buildings build between 1955-1978) 
* *National effect* (5): multiple industrial buildings located on the same zipcode + high gas usage + year of build (buildings build between 1955-1978)

In [17]:
# It seems like that Amsterdam-Zuid is slightly on the higher side regarding gas usage
df_env.describe()

,industrie,sport,x,y,lon,lat,gem_gas_woning,gem_gas_woning_cor,gem_elektriciteit_woning,gem_gas_bedrijf,gem_elektriciteit_bedrijf,potent_pand_asbest,gebouwen_gebruik_gas,meer_reg_woning,meer_reg_industrie
count,477.000000,477.000000,477.000000,477.000000,477.000000,477.000000,477.000000,477.000000,477.000000,477.000000,477.000000,477.000000,477.000000,477.000000,477.000000
mean,19.394130,1.161426,121464.722493,486198.535606,4.894866,52.362640,704.870021,818.295597,1902.316562,1578.888889,22908.312369,179.322851,943.773585,975.979036,16.442348
std,43.474225,2.509884,3593.393745,2965.826138,0.052826,0.026599,459.220325,533.059477,874.010111,4763.432756,63669.357088,431.819330,803.515905,770.842925,42.709830
min,0.000000,0.000000,111515.728019,477508.432833,4.748166,52.284786,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,119137.883999,484659.584087,4.860736,52.348759,370.000000,430.000000,1668.000000,0.000000,1085.000000,0.000000,193.000000,259.000000,0.000000
50%,5.000000,0.000000,121311.487722,486387.162874,4.892469,52.364416,777.000000,903.000000,1931.000000,153.000000,4322.000000,7.000000,820.000000,939.000000,3.000000
75%,18.000000,1.000000,124046.894309,488059.744142,4.932870,52.379278,954.000000,1108.000000,2364.000000,932.000000,17491.000000,68.000000,1461.000000,1516.000000,13.000000
max,560.000000,36.000000,130185.103090,493731.666667,5.022511,52.430227,3140.000000,3650.000000,5460.000000,54311.000000,771224.000000,2757.000000,3832.000000,3418.000000,558.000000

In [18]:
df_env['hoge_gas_verbruik'] = ((df_env['gem_gas_woning_cor'] >= 1155) | (df_env['gem_gas_bedrijf'] >= 7635))
df_env['hoge_gas_verbruik'] = list(map(int, df_env['hoge_gas_verbruik']))

# 1 = high gas usage and 0 = mediocre gas usage
print(df_env['hoge_gas_verbruik'].value_counts())

0    361
1    116
Name: hoge_gas_verbruik, dtype: int64

In [19]:
df_env['hoge_asbest_buurt'] = ((df_env['potent_pand_asbest'] >= 10)) # Arbitrarily set on 10 
df_env['hoge_asbest_buurt'] = list(map(int, df_env['hoge_asbest_buurt']))

# 1 = high gas usage and 0 = mediocre gas usage
print(df_env['hoge_asbest_buurt'].value_counts())

0    254
1    223
Name: hoge_asbest_buurt, dtype: int64

In [20]:
df_env['hoge_dichtheid_buurt'] = ((df_env['meer_reg_woning'] >= 1000)) # Arbitrarily set on 1000
df_env['hoge_dichtheid_buurt'] = list(map(int, df_env['hoge_dichtheid_buurt']))

# 1 = high density areas and 0 = low or no density areas
print(df_env['hoge_dichtheid_buurt'].value_counts())

0    254
1    223
Name: hoge_dichtheid_buurt, dtype: int64

In [21]:
df_env['industrie_buurt'] = ((df_env['meer_reg_industrie'] >= 1)) 
df_env['industrie_buurt'] = list(map(int, df_env['industrie_buurt']))

# 1 = neighborhood has industry and 0 = no industry located
print(df_env['industrie_buurt'].value_counts())

1    282
0    195
Name: industrie_buurt, dtype: int64

In [22]:
df_env['industriegebied'] = ((df_env['meer_reg_industrie'] >= 2)) # Arbitrarily set on 2
df_env['industriegebied'] = list(map(int, df_env['industriegebied']))

# 1 = neighborhood has more industries located and 0 = less than 2 industries located on zipcode level
print(df_env['industriegebied'].value_counts())

1    276
0    201
Name: industriegebied, dtype: int64

In [23]:
df_env['env_effect'] = df_env['hoge_gas_verbruik'] + df_env['hoge_asbest_buurt'] + df_env['hoge_dichtheid_buurt'] + df_env['industrie_buurt'] + df_env['industriegebied']
df_env

,buurtnaam,industrie,sport,x,y,lon,lat,gem_gas_woning,gem_gas_woning_cor,gem_elektriciteit_woning,...,potent_pand_asbest,gebouwen_gebruik_gas,meer_reg_woning,meer_reg_industrie,hoge_gas_verbruik,hoge_asbest_buurt,hoge_dichtheid_buurt,industrie_buurt,industriegebied,env_effect
0,,0.0,0.0,127272.953985,486387.342103,4.980127,52.364672,30.0,35.0,2978.0,...,0,10,456,0,0,0,0,0,0,0
1,AMC,17.0,0.0,125675.148825,478351.402025,4.957369,52.292367,0.0,0.0,0.0,...,0,0,0,16,0,0,0,1,1,2
2,Aalsmeerwegbuurt Oost,8.0,0.0,118367.772758,484680.376785,4.849575,52.348810,892.0,1036.0,1963.0,...,0,1332,1276,4,0,0,1,1,1,3
3,Aalsmeerwegbuurt West,2.0,2.0,118227.640354,484799.733183,4.847506,52.349873,832.0,966.0,1889.0,...,0,1515,1471,0,0,0,1,0,0,1
4,Afrikahaven,84.0,1.0,111515.728019,491259.693721,4.748166,52.407439,0.0,0.0,0.0,...,0,32,0,83,1,0,0,1,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
472,Zuidwestkwadrant Osdorp Noord,9.0,0.0,114680.708515,485444.267917,4.795373,52.355417,710.0,823.0,2256.0,...,347,1363,1295,9,0,1,1,1,1,4
473,Zuidwestkwadrant Osdorp Zuid,6.0,0.0,114829.990130,484998.734523,4.797618,52.351424,692.0,803.0,2432.0,...,313,2576,2549,5,0,1,1,1,1,4
474,Zunderdorp,9.0,2.0,126429.346139,491425.694498,4.967313,52.409910,1461.0,1696.0,3432.0,...,58,225,182,7,1,1,0,1,1,4
475,Zwarte Gouw,0.0,0.0,127337.106000,488663.413294,4.980881,52.385132,819.0,951.0,1958.0,...,16,32,32,0,0,1,0,0,0,1
476,de Plantage,15.0,1.0,122698.904550,486568.549507,4.912957,52.366051,983.0,1142.0,2138.0,...,12,1567,1415,7,0,1,1,1,1,4

In [24]:
df_env.dtypes

buurtnaam                     object
industrie                    float64
sport                        float64
x                            float64
y                            float64
lon                          float64
lat                          float64
gem_gas_woning               float64
gem_gas_woning_cor           float64
gem_elektriciteit_woning     float64
gem_gas_bedrijf              float64
gem_elektriciteit_bedrijf    float64
potent_pand_asbest             int64
gebouwen_gebruik_gas           int64
meer_reg_woning                int64
meer_reg_industrie             int64
hoge_gas_verbruik              int64
hoge_asbest_buurt              int64
hoge_dichtheid_buurt           int64
industrie_buurt                int64
industriegebied                int64
env_effect                     int64
dtype: object

In [25]:
print(df_env['env_effect'].value_counts().sort_index())

0     59
1     70
2    117
3    117
4    105
5      9
Name: env_effect, dtype: int64

In [26]:
df_env.to_csv('environment_effect_set.csv')